Dave's Weather Dashboard Submission :)
hackclub/asylum pull request #3
Opened 2024-12-24 04:29 UTC by dave9123

Hello!

Here is my weather station submission.

Thank you and have a great day :)

2025-01-31 19:57 UTC, Piplup7575 commented
No cavity included in the NFC tag

`@dave9123`
id: `U07C3SJ99RP`

![image](https://github.com/user-attachments/assets/10849b75-7b07-4e2e-b0e3-f960499992f0)

2025-02-11 20:21 UTC, qcoral requested changes
fix your nfc tag please! i also need a breakdown of the pricing in your BOM

2025-02-12 13:41 UTC, dave9123 commented
Whoops

2025-02-26 15:46 UTC, qcoral approved these changes
Okay - the cavity is a square but it should still work.

Congrats, your PR has been approved.

You can order it here:

forms.hackclub.com/asylum

(fill it out once per submission)

2025-02-26 15:47 UTC, merged

2025-02-26 23:02 UTC, dave9123 commented
Thank you :)